export const rpcUrls: Record<string, string[]> = {
    ethereum: ["https://rpc.ankr.com/eth"],
    sepolia: ["https://rpc.ankr.com/eth_sepolia"],
    avalanche: [
        "https://api.avax.network/ext/bc/C/rpc",
        "https://rpc.ankr.com/avalanche",
        "https://avalanche.public-rpc.com",
        "https://avalanche.drpc.org",
    ],
    avalancheFuji: ["https://avalanche-fuji-c-chain-rpc.publicnode.com"],
    arbitrum: [
        "https://arbitrum.blockpi.network/v1/rpc/public",
        "https://arbitrum.meowrpc.com",
        "https://rpc.ankr.com/arbitrum",
        "https://arbitrum-one-rpc.publicnode.com",
        "https://arbitrum.llamarpc.com",
    ],
    arbitrumSepolia: ["https://arbitrum-sepolia-rpc.publicnode.com"],
    optimism: [
        "https://optimism.blockpi.network/v1/rpc/public",
        "https://optimism.llamarpc.com",
        "https://rpc.ankr.com/optimism",
    ],
    optimismSepolia: ["https://rpc.ankr.com/optimism_sepolia"],
    polygon: [
        "https://polygon-bor-rpc.publicnode.com",
        "https://polygon.api.onfinality.io/public",
        "https://polygon-pokt.nodies.app",
        "https://polygon.llamarpc.com",
        "https://polygon-rpc.com",
        "https://rpc.ankr.com/polygon",
    ],
    polygonAmoy: ["https://polygon-amoy-bor-rpc.publicnode.com"],
    base: [
        "https://mainnet.base.org",
        "https://base.rpc.subquery.network/public",
        "https://base.gateway.tenderly.co",
        "https://base.meowrpc.com",
        "https://1rpc.io/base",
        "https://base-pokt.nodies.app",
        "https://rpc.ankr.com/base",
        `https://base-rpc.publicnode.com`,
    ],
    baseSepolia: ["https://base-sepolia-rpc.publicnode.com"],
    bsc: ["https://rpc.ankr.com/bsc"],
    scroll: ["https://rpc.ankr.com/scroll"],
    scrollSepolia: ["https://rpc.ankr.com/scroll_sepolia"],
}
