[profile.default]
solc = "0.8.28"
src = "./contracts/"
out = "foundry-artifacts"
cache_path = "cache/foundry"
test = "test/foundry"

libs = ["node_modules", "./src/contracts/"]
allow_paths = ["node_modules", "./src/contracts/"]

